name: creating workflow
on:
  # push:
  # pull_request: 
  # pull_request_review:
  #   types: [submitted]
  workflow_dispatch:
      
    
         
    #   branches:
    #       - main
    #       - feature
jobs:
  build:
       runs-on: ubuntu-latest
       steps:
          - run: echo "hello"

      
